In [16]:
#1. Import the NUMPY package under the name np.
import numpy as np

#2. Print the NUMPY version and the configuration.
#print(np.__version__)
print(np.version.version)

#3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
# Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?
a=np.random.random((2,3,5))

#4. Print a.
print(a)
print(np.size(a))

1.16.2
[[[0.58304021 0.1702276  0.5517037  0.46624177 0.70350309]
  [0.25536437 0.2743222  0.22045794 0.41227255 0.18220384]
  [0.67043578 0.26607086 0.05898789 0.92543738 0.79024992]]

 [[0.04644248 0.49066086 0.05011529 0.29745859 0.74829911]
  [0.75508864 0.51611852 0.69248121 0.08368705 0.44414208]
  [0.65414949 0.68211616 0.71254178 0.53619926 0.33822704]]]
30


In [17]:
#5. Create a 5x2x3 3-dimensional array with all values equaling 1.
#Assign the array to variable "b"
b = np.full((5,2,3), 3)
b.fill(1)

#6. Print b.
print(b)


[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


In [18]:
v = 1
rows = 2
cols = 3
y = np.tile(v, (rows,cols))
print(y) #try2

[[1 1 1]
 [1 1 1]]


In [19]:
array = np.arange(30).reshape(5,2,3)
array.fill(1)
print(array) #try3

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


In [157]:
#7. Do a and b have the same size? How do you prove that in Python code?
print("Size a", np.size(a), "Shape a", np.shape(a))
print("Size b", np.size(b), "Shape b", np.shape(b))


Size a 30 Shape a (2, 3, 5)
Size b 30 Shape b (5, 2, 3)


In [158]:
#8. Are you able to add a and b? Why or why not?
sumnp=np.add(a,b) #error as not the same structure of the shape , size is the same

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

In [159]:
#9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".
c=b.transpose(1,2,0)
print(c)

[[[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]


In [160]:
#10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?
d=np.add(a,c)
#11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.
print(d)

[[[1.58304021 1.1702276  1.5517037  1.46624177 1.70350309]
  [1.25536437 1.2743222  1.22045794 1.41227255 1.18220384]
  [1.67043578 1.26607086 1.05898789 1.92543738 1.79024992]]

 [[1.04644248 1.49066086 1.05011529 1.29745859 1.74829911]
  [1.75508864 1.51611852 1.69248121 1.08368705 1.44414208]
  [1.65414949 1.68211616 1.71254178 1.53619926 1.33822704]]]


In [161]:
#11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.
print(a)
print(d)
# à chaque element de la matrix a rajouté la valeur de chaque element de la matrix c

[[[0.58304021 0.1702276  0.5517037  0.46624177 0.70350309]
  [0.25536437 0.2743222  0.22045794 0.41227255 0.18220384]
  [0.67043578 0.26607086 0.05898789 0.92543738 0.79024992]]

 [[0.04644248 0.49066086 0.05011529 0.29745859 0.74829911]
  [0.75508864 0.51611852 0.69248121 0.08368705 0.44414208]
  [0.65414949 0.68211616 0.71254178 0.53619926 0.33822704]]]
[[[1.58304021 1.1702276  1.5517037  1.46624177 1.70350309]
  [1.25536437 1.2743222  1.22045794 1.41227255 1.18220384]
  [1.67043578 1.26607086 1.05898789 1.92543738 1.79024992]]

 [[1.04644248 1.49066086 1.05011529 1.29745859 1.74829911]
  [1.75508864 1.51611852 1.69248121 1.08368705 1.44414208]
  [1.65414949 1.68211616 1.71254178 1.53619926 1.33822704]]]


In [162]:
#12. Multiply a and c. Assign the result to e.

e=np.multiply(a,c)
print(e)

[[[0.58304021 0.1702276  0.5517037  0.46624177 0.70350309]
  [0.25536437 0.2743222  0.22045794 0.41227255 0.18220384]
  [0.67043578 0.26607086 0.05898789 0.92543738 0.79024992]]

 [[0.04644248 0.49066086 0.05011529 0.29745859 0.74829911]
  [0.75508864 0.51611852 0.69248121 0.08368705 0.44414208]
  [0.65414949 0.68211616 0.71254178 0.53619926 0.33822704]]]


In [186]:
#13. Does e equal to a? Why or why not?
#yes a=e, multiplcation by 1 gives the same number

#14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"

d_max=np.max(d)
d_min=np.min(d)
d_mean=np.mean(d)

In [187]:
#15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.
k=np.zeros([2, 3, 5])

#f=np.empty([2, 3, 5])

"""
#16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.
"""
#f=np.where((d < d_mean) & (d > d_min), 25, 0)
#f=np.where((d < d_max) & (d > d_mean), 75,0)
#f=np.where(d == d_min, 50, 0)
#f=np.where(d == d_max, 100, 0)

k=np.where((d < d_mean) & (d > d_min), 25, np.where((d < d_max) & (d > d_mean), 75,np.where(d == d_min, 50, np.where(d == d_max, 100, 0))))
print("d_max",d_max)
print("d_min",d_min)
print("d_mean",d_mean)
print("d",d)
print(k)

d_max 1.9254373791301904
d_min 1.0464424790903342
d_mean 1.4526082218767289
d [[[1.58304021 1.1702276  1.5517037  1.46624177 1.70350309]
  [1.25536437 1.2743222  1.22045794 1.41227255 1.18220384]
  [1.67043578 1.26607086 1.05898789 1.92543738 1.79024992]]

 [[1.04644248 1.49066086 1.05011529 1.29745859 1.74829911]
  [1.75508864 1.51611852 1.69248121 1.08368705 1.44414208]
  [1.65414949 1.68211616 1.71254178 1.53619926 1.33822704]]]
[[[ 75  25  75  75  75]
  [ 25  25  25  25  25]
  [ 75  25  25 100  75]]

 [[ 50  75  25  25  75]
  [ 75  75  75  25  25]
  [ 75  75  75  75  25]]]


In [183]:
Arr1=np.logical_and(d < d_mean, d > d_min)
for x in Arr1:
    for y in x:
        if Arr1[y]==True:
            y=25
        print(Arr1)
Arr2=np.logical_and(d < d_max, d > d_mean)
Arr3=d * (d == d_min)
Arr4=np.equal(d,d_max)
print(Arr1)
print(Arr2)
print(Arr3)
print(Arr4)

#equal(x1, x2, /[, out, where, casting, ...])


IndexError: boolean index did not match indexed array along dimension 0; dimension is 2 but corresponding boolean dimension is 5

In [190]:
#18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
"""("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question."""

k=np.where((d < d_mean) & (d > d_min), "D", np.where((d < d_max) & (d > d_mean), "B",np.where(d == d_min, "A", np.where(d == d_max, "E", "C"))))
print(k)

[[['B' 'D' 'B' 'B' 'B']
  ['D' 'D' 'D' 'D' 'D']
  ['B' 'D' 'D' 'E' 'B']]

 [['A' 'B' 'D' 'D' 'B']
  ['B' 'B' 'B' 'D' 'D']
  ['B' 'B' 'B' 'B' 'D']]]
